# Generated by Django 5.1 on 2024-08-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('player_position', models.CharField(choices=[('ST', 'Striker'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('AM', 'Attacking Midfielder'), ('DM', 'Defensive Midfielder'), ('LB', 'Left Back'), ('CB', 'Center Back'), ('RB', 'Right Back'), ('GK', 'Goal Keeper')], default='ST', max_length=2)),
                ('description', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
