# Generated by Django 5.1 on 2024-08-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/'),
        ),
    ]
