# Generated by Django 5.1 on 2024-08-21 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_player_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/player_images/'),
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy', models.CharField(choices=[('EPL', 'English Premier League'), ('UCL', 'UEFA Champions League'), ('FAC', 'Footballers Association Cup'), ('NON', 'No Trophies won this season!')], default='NON', max_length=3)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.player')),
            ],
        ),
    ]
