# Generated by Django 5.1 on 2024-08-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_player_profile_image_trophy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
                ('sell', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trophy',
            name='date',
            field=models.DateField(default=1, verbose_name='Trophy Date'),
            preserve_default=False,
        ),
    ]
